<?php

$title = 'Pay Checks';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<table class="table">
  <tr>
    <th>Id :: Personnel</th>
    <th>Gross Amount</th>
    <th>Net Amount</th>
    <th>Period</th>
    <th>Year</th>
    <th>&nbsp;</th>
  </tr>
  <?php foreach ($pays as $pay) :
    $personnel = $personnelTable->getPersonnel($pay->personnelId);
    ?>
  <tr>
    <td><?php echo $this->escapeHtml($personnel->personnelId.' :: '.$personnel->fName.' '.$personnel->lName);?></td>
    <td><?php echo $this->escapeHtml('$'.$pay->grossAmount);?></td>
    <td><?php echo $this->escapeHtml('$'.$pay->netAmount);?></td>
    <td><?php echo $this->escapeHtml($pay->period);?></td>
    <td><?php echo $this->escapeHtml($pay->year);?></td>
    <td>
      <a class="btn btn-info" href="<?php echo $this->url('pay',array('action' => 'payslip','id' => $pay->payId));?>">View</a>
      <a class="btn btn-success" href="<?php echo $this->url('pay',array('action' => 'add','id' => $pay->payId));?>">Add Deduction</a>
      <a class="btn btn-warning" href="<?php echo $this->url('pay',array('action' => 'print','id' => $pay->payId));?>">Print</a>
      <a class="btn btn-danger" href="<?php echo $this->url('pay',array('action' => 'delete','id' => $pay->payId));?>">Delete</a>
    </td>
  </tr>
<?php endforeach; ?>
</table>
