<?php

$title = 'Payslip';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php $info = explode(",",$buffer); ?>
<p>Name:<?php echo $info[0]; ?></p>
<p>Gross Pay:<?php echo $info[1]; ?></p>
<p>Net Pay:<?php echo $info[2]; ?></p>
<p>Period:<?php echo $info[3]; ?></p>
<p>Year:<?php echo $info[4]; ?></p>
<hr/>
<p style="text-decoration:underline;">Deductions</p>
<?php
  for ($i=5;$i<sizeof($info);$i++)
  {
    ?>
    <p>
      <?php echo $info[$i]; ?>
    </p>
    <?php
  }
 ?>
