<?php

$title = 'Payslip';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Name:<?php $personnel = $getPersonnelTable->getPersonnel($payDetails->personnelId); echo $personnel->fName.' '.$personnel->lName; ?></p>
<p>Gross Pay:$<?php echo $payDetails->grossAmount; ?></p>
<p>Net Pay:$<?php echo $payDetails->netAmount; ?></p>
<p>Period:<?php echo $payDetails->period; ?></p>
<p>Year:<?php echo $payDetails->year; ?></p>
<hr/>
<p style="text-decoration:underline;">Deductions</p>
<?php
  $deductions = explode(",",$payDetails->appliedDeductions);
  foreach ($deductions as $deduction):
    ?>
    <p>
      <?php echo $deduction; ?>
    </p>
    <?php
  endforeach;
 ?>
