<?php

$title = 'Add new deduction';
$this->headTitle($title);
$this->headScript()->appendFile('/js/deductionValidator.js');

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action',$this->url('deduction',array('action' => 'add')));
$form->setAttribute('onsubmit','return isFormValid()');
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('deduction_id'));
?>

<div class='form-group'>
<?php
echo $this->formRow($form->get('deduction_name'));
?>
<br/><span id='deduction_name'></span>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('deduction_percentage'));
?>
<br/><span id='deduction_percentage'></span>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('fixed_amount'));
?>
<br/><span id='fixed_amount'></span>
</div>

<div class='form-group'>
<label>Should this tax deduction be applied to all employees every period ?</label>
<br/>
<?php
echo $this->formRadio($form->get('periodic_deduction'));
?>
</div>

<?php
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
