<?php

$title = 'Add new personnel';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action',$this->url('personnel',array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('personnel_id'));
?>
<div class='form-group'>
<?php
echo $this->formRow($form->get('fname'));
?>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('lname'));
?>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('age'));
?>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('street_name'));
?>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('community'));
?>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('parish'));
?>
</div>

<div class='form-group'>
<label>Gender</label>
<br/>
<?php
echo $this->formSelect($form->get('gender'));
?>
</div>

<?php
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
