<?php

$title = 'Add new personnel';
$this->headTitle($title);
$this->headScript()->appendFile('/js/personnelValidator.js');

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action',$this->url('personnel',array('action' => 'add')));
$form->setAttribute('onsubmit','return isFormValid()');
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('personnel_id'));
?>
<div class='form-group'>
<?php
echo $this->formRow($form->get('fname'));
?>
<br/><span id='fname'></span>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('lname'));
?>
<br/><span id='lname'></span>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('age'));
?>
<br/><span id='age'></span>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('street_name'));
?>
<br/><span id='street_name'></span>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('community'));
?>
<br/><span id='community'></span>
</div>

<div class='form-group'>
<?php
echo $this->formSelect($form->get('parish'));
?>
</div>

<div class='form-group'>
<label>Gender</label>
<br/>
<?php
echo $this->formSelect($form->get('gender'));
?>
</div>

<?php
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
