<?php

$title = 'Remove personnel';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to remove
  '<?php echo $this->escapeHtml($personnel->fName.' '.$personnel->lName); ?>' ?
</p>
<?php
$url = $this->url('personnel',array(
  'action' => 'delete',
  'id' => $this->id,
));
?>

<form action="<?php echo $url; ?>" method="post">
  <div>
    <input type="hidden" name="id" value="<?php echo (int) $personnel->personnelId; ?>" />
    <input type="submit" class="btn btn-default" name="del" value="Yes" />
    <input type="submit" class="btn btn-default" name="del" value="No" />
  </div>
</form>
