<?php

$title = 'Employees';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p >
  <a class="btn btn-success" href="<?php echo $this->url('personnel',array('action'=>'add'));?>">Add new personnel</a>
</p>

<div class="row">



<p class="col-sm-1">
  <a class="btn btn-info" href="<?php echo $this->url('task',array('action'=>'index'));?>">Tasks</a>
</p>

<p class="col-sm-1">
  <a class="btn btn-info" href="<?php echo $this->url('location',array('action'=>'index'));?>">Locations</a>
</p>

<p class="col-sm-2">
  <a class="btn btn-info" href="<?php echo $this->url('work-done',array('action'=>'index'));?>">View works done</a>
</p>

<p class="col-sm-2">
  <a class="btn btn-info" href="<?php echo $this->url('personnel-task',array('action'=>'index'));?>">Assign Tasks</a>
</p>

<p class="col-sm-2">
  <a class="btn btn-info" href="<?php echo $this->url('pay',array('action'=>'index'));?>">View Pay History</a>
</p>

<p class="col-sm-4">
</p>

</div>


<table class="table">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Age</th>
    <th>Address</th>
    <th>Gender</th>
    <th>&nbsp;</th>
  </tr>
  <?php foreach ($personnels as $personnel) :
    $address = $addressTable->getAddress($personnel->address);
    ?>
  <tr>
    <td><?php echo $this->escapeHtml($personnel->fName);?></td>
    <td><?php echo $this->escapeHtml($personnel->lName);?></td>
    <td><?php echo $this->escapeHtml($personnel->age);?></td>
    <td><?php echo $this->escapeHtml($address->streetName.', '.$address->community.', '.$address->parish);?></td>
    <td><?php echo $this->escapeHtml($personnel->gender);?></td>
    <td>
      <a class="btn btn-primary" href="<?php echo $this->url('personnel',array('action' => 'edit','id' => $personnel->personnelId));?>">Edit</a>
      <a class="btn btn-danger" href="<?php echo $this->url('personnel',array('action' => 'delete','id' => $personnel->personnelId));?>">Delete</a>
    </td>
  </tr>
<?php endforeach; ?>
</table>
