<?php

$title = 'Delete  record of work done';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to remove this record of work done?
</p>
<?php
$url = $this->url('work-done',array(
  'action' => 'delete',
  'id' => $this->id,
));
?>

<form action="<?php echo $url; ?>" method="post">
  <div>
    <input type="hidden" name="id" value="<?php echo (int) $workDone->workId; ?>" />
    <input type="submit" class="btn btn-default" name="del" value="Yes" />
    <input type="submit" class="btn btn-default" name="del" value="No" />
  </div>
</form>
