<?php

$title = 'Edit address';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action',$this->url('address',
  array(
    'action' => 'edit',
    'id' => $this->id,
  )
));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('addr_id'));
?>
<div class='form-group'>
<?php
echo $this->formRow($form->get('street_name'));
?>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('community'));
?>
</div>

<div class='form-group'>
<?php
echo $this->formRow($form->get('parish'));
?>
</div>

<?php
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
