<?php

$title = 'Add new task';
$this->headTitle($title);
$this->headScript()->appendFile('/js/taskValidator.js');

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action',$this->url('task',array('action' => 'add')));
$form->setAttribute('onsubmit','return isFormValid()');
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('task_id'));
?>
<div class='form-group'>
<?php
echo $this->formRow($form->get('task_name'));
?>
<br/><span id='task_name'></span>
</div>

<?php
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
