<?php

$title = 'Edit task';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action',$this->url('task',
  array(
    'action' => 'edit',
    'id' => $this->id,
  )
));

$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('task_id'));
?>
<div class='form-group'>
<?php
echo $this->formRow($form->get('task_name'));
?>
</div>

<?php
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
